sources:
    - name: jaffle_shop
      description: This is a replica of the Postgres database used by our app
      database: dbtdemo_dev
      schema: raw_jaffle
      tables:
          - name: customers
            description: One record per customer.
          - name: orders
            description: One record per order. Includes cancelled and deleted orders.